### ISSUE TITLE
باگ در اندازه نقطه ها

### ISSUE THREAD

**Issue by xawir** [MDarvishi5124/Arad#3]
سلام، امیدوارم حالتون خوب باشه،
و خسته نباشيد حسابی برای طراحی این فونت خیلی زیبا ❤️. 

![20240802_172425.jpg](https://github.com/user-attachments/assets/9f7283bd-a70a-4951-97e2-1f6146a7059c)

یه باگ ریز هست برای نقطه ها در وزن های نازک که در وزن Thin کاملا محو میشود و تناسب نقطه ها
![IMG_20240802_174444.jpg](https://github.com/user-attachments/assets/520ff898-9e71-4b6b-98be-a6ad82890cb9)

امیدوارم تست هام درست باشه🫠 (با گوشی و نرمافزار PixelLab انجام دادم)

**Comment by MDarvishi5124** [comment]
قبل هر چیزی؛ نسخۀ 0.9.2 منتشر شده و این باگ رفع شده
https://github.com/MDarvishi5124/Arad/releases/tag/v0.9.2b

البته بهتر هست سوال رو در قسمت discussions پروژه بگید. تکنولوژی فونت وربیل، توی اندروید هست؛ اما اینکه برنامه‌ای قابلیت استفاده ازش رو داشته باشه، به خود برنامه بستگی داره. من تابحال ندیدم برنامۀ ویرایش تصویر یا ساخت ویدیو، توی اندروید چنین ویژگی‌ای رو پیاده کرده باشه. بخاطر همینه که فونت وربیل، کاربردش رو توی این جور مسائل از دست میده.
