### ISSUE TITLE
فونت جدید شبیه به ساحل یا فرهنگ

### ISSUE THREAD

**Issue by itskazemk** [MDarvishi5124/Arad#6]
خسته نباشید واقعا، ممنونم از تلاشتون برای ایجاد فونت های فارسی زیبا و با کیفیت و همچنین آزاد که سطح کیفیت وب ایران رو بالا می برن.
درخواستم اینکه در صورت امکان فونتی شبیه به ساحل یا فرهنگ بسازین که همزان شکستی‌ها و زیبایی‌ها داشته باشه و همزان سطح بالای خوانایی.
من در حوزه طراحی فونت تخصصی ندارم اما اگه بتونین فورک فونت ساحل هم ادامه بدین عالی میشه.

**Comment by MDarvishi5124** [comment]
سلام. ممنونم. من در حال حاضر، شرایط خیلی جالبی ندارم. موارد دیگه‌ای هست که در حال حاضر، اولویتشون برام بیشتر از توسعۀ فونت هست. بخاطر همین زمان زیادی رو به توسعۀ فونت نمی‌تونم اختصاص بدم. پیشنهاد فورک ساحل، پیشنهاد خوبی هست، اما من اگه وقت داشته باشم، بیشتر از فورک ساحل، علاقه دارم فونت های فعلیم رو به یک مرحلۀ خوب از توسعه رسونده باشم. فونت آراد نیاز به یک بازطراحی داره، فونت یونیکسل هم نیاز به یک بازسازی کلی و گسترش داره. بعد اینها، من می‌تونم به توسعۀ فونت دیگه‌ای هم فکر کنم. اما در حال حاضر، کلاً نمی‌تونم به توسعۀ فونت بپردازم.

**Comment by ahangarha** [comment]
البته که این درخواست ارتباطی با این پروژه نداره اما چه کاستی‌هایی در ساحل می‌بینید که نیاز به اصلاح و ساخت فونت جدید داشته باشه؟
@itskazemk

**Comment by MDarvishi5124** [comment]
بنظر میاد از لحاظ هنری، نیاز داره یه دستی به سر و روش کشیده بشه. از طرفی الان فونت متغیر خوبی نداره، و کامل نیست.
البته ساحل می‌تونه یه محور کنتراست هم داشته باشه.
@ahangarha

**Comment by ahangarha** [comment]
غیر از مواردی که مربوط به نسخهٔ متغیر می‌شه، خوشحال می‌شم اگر بتونم کمکی بکنم.
