### ISSUE TITLE
مشکل بهم ریختگی stroke فونت

### ISSUE THREAD

**Issue by UnrivaledIr** [MDarvishi5124/Arad#9]
درود و عرض ادب.

ضمن تشکر از شما و تلاش‌هایتان بابت فونت زیبای آراد احتراما فونت بعد از اعمال stroke در نرم‌افزار Inkscape دچار مشکل بهم‌ریختگی می‌شود. امیدوارم تصویر ضمیمه گویای مشکل باشد.

مشکل هم در فونتی که از گیت‌هاب دانلود کردم و هم از طریق AUR (آرچ) یکسان بود.
نسخه فونت : arad-fonts   1.0.1-1

![Screenshot_20241118_112935](https://github.com/user-attachments/assets/b235b973-4b8b-4689-aa89-8c5381f4796b)

**Comment by MohamadDarvishi** [comment]
سلام، از اکانت دیگه‌ای پاسخگو هستم. این مشکل نرم افزاری هست و ارتباطی با فونت نداره. این مشکل حتی تو ایلستریتور هم هست و به نرم افزار مربوطه.

**Comment by UnrivaledIr** [comment]
سپاس از شما. بله من فراموش کردم که ببندم ایشو رو.
خد ا رو شکر حداقل ثبت شد تا دوستان دیگه‌ای که به چنین مشکلی برخورد کردند بدونن مشکل از نرم‌افزار هست.
سپاس از شما
